name: Main Pipeline

# triggers on any push to the branch when any file other than a markdown file is changed
on:
  push:
    branches: ["main"]
    paths-ignore: ["**.md", "**.txt"]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:    
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
  
      - name: install app dependencies
        working-directory: ./app
        run: flutter pub get

      - name: Set up lcov
        run: |
          sudo apt-get update -qq -y
          sudo apt-get install lcov -y

      #- name: Run Tests 
      #  run: flutter test --coverage
      #- name: Report code coverage
      # uses: zgosalvez/github-actions-report-lcov@v3
      # with:
      #    coverage-files: lcov.info
      #    minimum-coverage: 50
      #    github-token: ${{ secrets.GITHUB_TOKEN }}
      #    working-directory: ./coverage
      #    update-comment: true
          
      #- name: Run tests
      #  working-directory: ./app
      #  run: flutter test

      - name: Build flutter web
        working-directory: ./app
        run: flutter build web
     
      - name: Web Deploy - GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./app/build/web/
  #deploy:
   # runs-on: ubuntu-latest
    #steps:
     # - name: Web Deploy - GitHub Pages
      #  uses: peaceiris/actions-gh-pages@v3
       # with:
        #  github_token: ${{ secrets.GITHUB_TOKEN }}
         # publish_dir: ./app/build/web/
