name: Main Pipeline

on:
  push:
    branches: ["permissionsAuto"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:    
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Clone into Repo
        run: git clone https://github.com/tkleg/CSC325Pipeline.git
    
      - name: install app dependencies
        working-directory: ./app
        run: flutter pub get

      - name: Run tests
        working-directory: ./app
        run: flutter test

      - name: Build flutter web
        working-directory: ./app
        run: flutter build web

      - name: see path
        run: pwd

      - name: Deploy
        run: echo "Calling deploy.yml"

  deploy:
    steps:
      - name: Web Deploy - GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./app/build/web/