name: Deploy Flutter Web Application

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:    
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

          
      - name: Confirm Run
        run: echo "deploy.yml called and ran"