name: Deploy Flutter Web Application

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:    
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Web Deploy - GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
         publish_dir: ./app/build/web/
         
      - name: Confirm Run
        run: echo "deploy.yml called and ran"